### ISSUE TITLE
Locally created Docker image is not working.

### ISSUE THREAD

**Issue by jaganmani5** [elmsln/WCFactory#553] opened 2019-06-03 10:14 UTC
Hi,

I have pulled Wcfactory code and run docker-compose build in my local,
when image is created, i am trying to run that image, but its throwing below error.

C:\temp\WCFactory>docker-compose run wcfactory -h
Creating network "wcfactory_default" with the default driver
/usr/bin/env: 'node\r': No such file or directory

Could you please resolve this issue.

Thanks,
Jagan.

**Comment by btopro** [comment] 2019-06-03 16:32
#546 duplicate of this issue. We do not maintain the docker hub image and we have it marked to be removed. Please install locally.

**Closed by btopro** 2019-06-03 16:32 UTC
