### ISSUE TITLE
TypeError: chalk.yellowBright is not a function

### ISSUE THREAD

**Issue by azinck** [elmsln/wcfactory#162] opened 2018-11-08 16:43 UTC
Seeing this error when trying to generate a vanilla JS element with no HAX or SASS support.  Here's a little more context for the error:

```yarn install v1.12.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@storybook/addon-a11y > @emotion/styled > @emotion/styled-base@0.10.6" has unmet peer dependency "@emotion/core@0.x.x".
warning " > @storybook/polymer@4.0.4" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".
warning " > @storybook/polymer@4.0.4" has unmet peer dependency "lit-html@0.10.0".
warning "@storybook/polymer > @storybook/core@4.0.4" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".
[4/4] 📃  Building fresh packages...
✨  Done in 18.12s.
yarn run v1.12.1
$ ../../node_modules/.bin/gulp && ../../node_modules/.bin/rollup -c && ../../node_modules/.bin/prettier --ignore-path ../../.prettierignore --write '**/*.{js,json}'
[11:30:43] Using gulpfile ~/wcfactory-test/factories/wcfactory-test/elements/popup-info/gulpfile.js
[11:30:43] Starting 'default'...
[11:30:43] Starting 'merge'...
[11:30:43] Finished 'merge' after 55 ms
[11:30:43] Starting 'analyze'...
[11:30:48] Finished 'analyze' after 4.28 s
[11:30:48] Starting 'build'...
[11:31:03] Finished 'build' after 15 s
[11:31:03] Starting 'compile'...
child process exited with code 0
[11:31:03] Finished 'compile' after 31 ms
[11:31:03] Starting 'sourcemaps'...
[11:31:03] Finished 'sourcemaps' after 15 ms
[11:31:03] Finished 'default' after 20 s

popup-info.umd.js → popup-info.umd.js...
created popup-info.umd.js in 2.7s
analysis.json 87ms
build/es5-amd/popup-info.js 125ms
build/es6/popup-info.js 69ms
build/polymer.json 37ms
gulpfile.js 144ms
polymer.json 33ms
popup-info.js 67ms
popup-info.story.js 78ms
rollup.config.js 28ms
src/popup-info-hax.json 22ms
src/popup-info-properties.json 24ms
src/popup-info.js 45ms
✨  Done in 26.16s.
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: chalk.yellowBright is not a function
    at module.exports.end (/Users/azinck/.config/yarn/global/node_modules/@wcfactory/generator-wcfactory/generators/element/index.js:374:13)
    at Object.<anonymous> (/Users/azinck/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:424:27)
    at /Users/azinck/.config/yarn/global/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/azinck/.config/yarn/global/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/azinck/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:425:13)
    at processImmediate (timers.js:632:19)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/azinck/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:433:22)
    at processImmediate (timers.js:632:19)
```

**Comment by btopro** [comment] 2018-11-08 17:51
hmmm can you check on the node version you have?  yellowBright exists in the chalk version specified. Did you do yarn install at the mono-repo root prior to issueing `wcf element`?

**Comment by azinck** [comment] 2018-11-08 18:00
I'm running node 11.1 -- and I do see yellowBright in chalk in my node_modules directory (it's also in the version of ansi-styles I have).

I didn't explicitly call yarn install in the mono-repo root (though I assume that's handled by some of the other automation you have in place?).

I've now tested again by first running `yarn install` in the mono-repo root, then trying to use `wcf element` again and I get the same exact problem.

**Comment by btopro** [comment] 2018-11-08 18:59
hmm... odd. I have not tested this with node 11; 8 and 10 yes. Would you be able to switch to one of those and try perhaps?

**Comment by azinck** [comment] 2018-11-08 22:31
I switched to node 10.13.0 and started the process from scratch (destroyed my entire wcfactory directory). I ran through the process again, and when I got to the `wcf element` step I ran into the same error. 

Now, I've been unintentionally withholding info. Yesterday I ran into a similar, but different error at the same point:

```yarn install v1.12.1
[1/4] 🔍  Resolving packages...
warning workspace-aggregator-a1205e04-3d38-4c4b-b7af-4d40287db15b > @azinck/popup-info > polymer-cli > bower@1.8.2: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
warning workspace-aggregator-a1205e04-3d38-4c4b-b7af-4d40287db15b > @azinck/popup-info > polymer-cli > github@7.3.2: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@storybook/addon-a11y > @emotion/styled > @emotion/styled-base@0.10.6" has unmet peer dependency "@emotion/core@0.x.x".
warning " > @storybook/polymer@4.0.4" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".
warning " > @storybook/polymer@4.0.4" has unmet peer dependency "lit-html@0.10.0".
warning "@storybook/polymer > @storybook/core@4.0.4" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 18.76s.
yarn run v1.12.1
$ ../../node_modules/.bin/gulp && ../../node_modules/.bin/rollup -c && ../../node_modules/.bin/prettier --ignore-path ../../.prettierignore --write '**/*.{js,json}'
[16:47:31] Using gulpfile ~/wcfactory-test/factories/wcfactory-test/elements/popup-info/gulpfile.js
[16:47:31] Starting 'default'...
[16:47:31] Starting 'merge'...
[16:47:31] Finished 'merge' after 27 ms
[16:47:31] Starting 'analyze'...
[16:47:35] Finished 'analyze' after 3.71 s
[16:47:35] Starting 'build'...
[16:47:45] Finished 'build' after 9.75 s
[16:47:45] Starting 'compile'...
child process exited with code 0
[16:47:45] Finished 'compile' after 29 ms
[16:47:45] Starting 'sourcemaps'...
[16:47:45] Finished 'sourcemaps' after 10 ms
[16:47:45] Finished 'default' after 14 s

popup-info.umd.js → popup-info.umd.js...
created popup-info.umd.js in 1.4s
analysis.json 48ms
build/es5-amd/popup-info.js 63ms
build/es6/popup-info.js 39ms
build/polymer.json 15ms
gulpfile.js 62ms
polymer.json 16ms
popup-info.js 37ms
popup-info.story.js 29ms
rollup.config.js 10ms
src/popup-info-hax.json 6ms
src/popup-info-properties.json 9ms
src/popup-info.js 25ms
✨  Done in 17.28s.
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn lerna ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

To try to resolve this I installed lerna globally.  After I did that, I then began to receive the chalk.yellowBright is not a function error.  Enough time had passed between testing these things (been fitting this in around meetings today) that I re-tested today (now with node 10) just to confirm this was really what I was seeing.  I can confirm that it is: when lerna is installed globally I get the `chalk.yellowBright is not a function` problem, and when it's *not* installed globally I get the `Error: spawn lerna ENOENT` problem.

I'm a little perplexed because both lerna and chalk are most definitely present in my factory's node_modules directory.

**Comment by btopro** [comment] 2018-11-08 23:40
`warning workspace-aggregator-a1205e04-3d38-4c4b-b7af-4d40287db15b > @azinck/popup-info > polymer-cli > bower@1.8.2: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/` is already odd because we're not using bower and nothing we use pulls in bower so that shouldn't show up

**Comment by btopro** [comment] 2018-11-17 15:04
if you try w/ 0.5.0 do you experience this same issue?

**Comment by btopro** [comment] 2018-11-30 01:49
@azinck was this on a PC perchance?

**Comment by azinck** [comment] 2018-11-30 01:52
No, MacOS.

**Comment by btopro** [comment] 2018-11-30 02:09
odd. I just published a new version if you could run `yarn global add @wcfactory/cli` to get 0.6.0 and see if running `wcf element` produces the same error?

**Comment by btopro** [comment] 2018-11-30 02:54
confirmed on a PC that 0.6.0 will fix the brightYellow error. It would appear that we might need lerna to be installed globally, manually in order to utilize the link command we're issuing in our build step initially after producing an element

**Comment by btopro** [comment] 2018-11-30 02:55
I won't close this till you confirm but publishing 0.6.1 right now which takes out lerna global and the bright calls. bright seems to be an issue w/ certain terminals that don't have access to that color

**Comment by btopro** [comment] 2018-11-30 20:56
this is resolved as of 0.6.1

**Closed by btopro** 2018-11-30 20:56 UTC

**Comment by azinck** [comment] 2018-11-30 22:47
@btopro Thanks for your work on this.  I can confirm this does resolve the problem for me!  I was able to successfully generate an element without hitting either the yellowBright error OR the Error: spawn lerna ENOENT error.  And that's without having lerna installed globally.

This is on MacOS which currently has node 11.3.0 installed.

**Comment by btopro** [comment] 2018-12-01 00:57
Excellent. Anything else let us know
